### PR TITLE
Codecov

### PR DESCRIPTION
**Pull request by pawurb**
Not ready yet, submitting to run the CI and see result

### CODE REVIEW

**Comment by omaralbeik** [comment]
@pawurb do you think deleting the entire project from Codecov and re-adding it again might help?

**Comment by pawurb** [comment]
I don't think so. Looks like coverage data report is not generated. I'll try different config options.

**Comment by pawurb** [comment]
@omaralbeik I tried the same config as for SwifterSwift, and couple tweaks but nothing seems to work.  It looks like coverage data generation might have changed between xcode 8 and 9. 

I no longer work in iOS, if you find any OS project that is reporting coverage data and using travis with xCode 9, let me know and I will probably be able to copy the config.

As a last resort maybe you can try readding project to codecov ;)

**Comment by omaralbeik** [comment]
Thank you @pawurb, I think it is a bug in Codecov, I have other projects in Xcode 9 running without any problem, even SwifterSwift is running in Xcode 9, I'll try to delete the entire project from Codecov and add it again

**Pull request closed without merging**
